name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --target rewindviewer --parallel 6 --config Release
    
    - name: Copy assets
      run: cp -R ./resources ./build/Release
      shell: bash
    
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: rewindviewer_win
        path: build/Release
